package com.trimlink.module.payment.entity;

import com.trimlink.common.audit.BaseEntity;
import com.trimlink.module.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Payment record — one per booking or queue entry.
 *
 * Idempotency is enforced via the tx_ref column (unique per provider transaction).
 * Webhooks check this column before processing to prevent double-processing.
 *
 * The idempotency_key is generated by us on initiation; it equals the tx_ref
 * we send to the gateway, and is the key used in idempotency checks.
 */
@Entity
@Table(name = "payments", indexes = {
        @Index(name = "idx_payment_tx_ref",    columnList = "tx_ref", unique = true),
        @Index(name = "idx_payment_user",      columnList = "user_id"),
        @Index(name = "idx_payment_status",    columnList = "status"),
        @Index(name = "idx_payment_reference", columnList = "reference_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Reference ID: UUID of the Appointment or QueueEntry being paid for.
     * We use a String + type instead of a JPA relationship to keep payment module decoupled.
     */
    @Column(name = "reference_id", nullable = false, columnDefinition = "uuid")
    private UUID referenceId;

    @Enumerated(EnumType.STRING)
    @Column(name = "reference_type", nullable = false, length = 20)
    private PaymentReferenceType referenceType;  // APPOINTMENT or QUEUE_ENTRY

    @Enumerated(EnumType.STRING)
    @Column(name = "provider", nullable = false, length = 20)
    private PaymentProvider provider;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private PaymentStatus status = PaymentStatus.PENDING;

    @Column(name = "amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false, length = 5)
    @Builder.Default
    private String currency = "ETB";

    /**
     * Transaction reference sent TO the payment gateway.
     * Used as the idempotency key for webhook deduplication.
     * Format: "TRIM-{UUID}" — unique per payment attempt.
     */
    @Column(name = "tx_ref", nullable = false, unique = true, length = 100)
    private String txRef;

    /**
     * Checkout URL returned by the gateway — sent to the client to redirect for payment.
     */
    @Column(name = "checkout_url", length = 500)
    private String checkoutUrl;

    /**
     * Provider's own transaction ID (received in webhook callback).
     */
    @Column(name = "provider_tx_id", length = 200)
    private String providerTxId;

    /** Full webhook payload stored for audit / replay. */
    @Column(name = "webhook_payload", columnDefinition = "TEXT")
    private String webhookPayload;

    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    @Column(name = "failed_reason", length = 500)
    private String failedReason;

    // ─── Status transitions ────────────────────────────────────────────────

    public void markSuccess(String providerTxId, String webhookPayload) {
        this.status        = PaymentStatus.SUCCESS;
        this.providerTxId  = providerTxId;
        this.webhookPayload = webhookPayload;
        this.paidAt        = LocalDateTime.now();
    }

    public void markFailed(String reason, String webhookPayload) {
        this.status          = PaymentStatus.FAILED;
        this.failedReason    = reason;
        this.webhookPayload  = webhookPayload;
    }
}
